version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup'
          command: |
            virtualenv -p python3 ~/.virtualenvs/tap-marketo
            source ~/.virtualenvs/tap-marketo/bin/activate
            pip install .[test]
            pip install pylint
      - run:
          name: 'Pylint'
          command: |
            source ~/.virtualenvs/tap-marketo/bin/activate
            pylint tap_marketo -d C,R,W
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_marketo/schemas/*.json
      - run:
          name: 'Unit Tests'
          command: |
            source ~/.virtualenvs/tap-marketo/bin/activate
            pip install nose2 parameterized nose2[coverage_plugin]>=0.6.5
            nose2 --with-coverage -v -s tests
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      # - add_ssh_keys
      # - run:
      #     name: 'Integration Tests'
      #     command: |
      #       aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/sandbox dev_env.sh
      #       source dev_env.sh
      #       source /usr/local/share/virtualenvs/tap-tester/bin/activate
      #       run-a-test --tap=tap-marketo \
      #                  --target=target-stitch \
      #                  --orchestrator=stitch-orchestrator \
      #                  --email=harrison+sandboxtest@stitchdata.com \
      #                  --password=$SANDBOX_PASSWORD \
      #                  --client-id=50 \
      #                  tap_tester.suites.marketo
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
